### ISSUE TITLE
Not Really an Issue

### ISSUE THREAD

**Issue by ZellW** [wesslen/iviz-rstudio-workshop#1]
Where do I sign up for the start of this event scheduled for July 18 at Packard Place in Charlotte?

**Comment by wesslen** [comment]
Hi Cliff- Thanks for your note. Are you a current or former UNCC DSI (DSBA or Health Informatics, certificate or master's) student? Unfortunately, this workshop is only open to these students (it was paid by UNCC DSI). Even worse, we've already booked at capacity. 

However, I appreciate your interest as we've received several requests. I'm going to take this back to the program directors to mention the interest in general. There's a chance I may try to have a public workshop again, perhaps this time partnering with the Davidson Machine Learning group. If you're interested, let me know and I'll try to reach back out if we get it to happen.
